name: data-science-at-scale
channels:
  - conda-forge
dependencies:
  - python=3.8
  - bokeh
  - dask
  - distributed
  - dask-labextension
  - jupyterlab
  - nodejs=14
  - dask-ml
  - numpy
  - pandas
  - pyarrow
  - python-graphviz
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - requests
  - pytables
  - s3fs
